services:
  vector_store:
    image: qdrant/qdrant
    container_name: rag_qdrant
    ports:
    - 6333:6333
    env_file:
    - .env
  frontend:
    build:
      context: frontend
    container_name: rag_streamlit
    ports:
    - 8501:8501
    environment:
      API_HOST: api
    env_file:
    - .env
  ollama:
    image: ollama/ollama
    container_name: ollama2
    volumes:
      - ollama:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    ports:
      - "11434:11434"
    entrypoint: ["/usr/bin/bash", "entrypoint.sh"]
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s
      timeout: 10s
      retries: 5
  api:
    build: 
      context: .
      dockerfile: backend/Dockerfile
    container_name: rag_api
    ports:
      - 7860:7860
    environment:
      OLLAMA_HOST: ollama
      QDRANT_HOST: vector_store
      QDRANT_PORT: 6333
    env_file:
      - .env
    depends_on:
      ollama:
        condition: service_healthy
volumes:
  ollama:
